name: bank_app0
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  community_material_icon: ^5.9.55
  material_design_icons_flutter: ^7.0.7296
  ionicons: ^0.2.2
  antdesign_icons: ^0.0.3
  ant_design_flutter: ^0.0.1+5
  flutter_feather_icons: ^2.0.0+1
  animated_bottom_navigation_bar: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
